# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-18 08:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("geo", "0019_auto_20180308_1912"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="campusonline",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="geo",
                to="campusonline.Room",
            ),
        ),
    ]
