# Generated by Django 2.2.28 on 2022-12-19 16:28

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0021_auto_20200805_1403'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='node',
            options={'get_latest_by': 'modified'},
        ),
        migrations.AlterModelOptions(
            name='pointofinterestinstance',
            options={'get_latest_by': 'modified'},
        ),
        migrations.AlterField(
            model_name='level',
            name='order',
            field=models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='pointofinterest',
            name='order',
            field=models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='room',
            name='layout',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=3857),
        ),
    ]
