# Generated by Django 5.2.16 on 2026-09-08 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("geo", "0022_auto_20221219_1728"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="room",
            options={"ordering": ("campusonline__name_full",)},
        ),
        migrations.AddField(
            model_name="edgecategory",
            name="duration_formula",
            field=models.TextField(
                blank=True,
                default="length / 1.4",
                help_text="Formula for duration calculation. Available variables: length, floors. Example: '30 + (floors * 3)'",
            ),
        ),
        migrations.AlterField(
            model_name="node",
            name="polymorphic_ctype",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="polymorphic_%(app_label)s.%(class)s_set+",
                to="contenttypes.contenttype",
            ),
        ),
    ]
